profile: cover.out

local-prefix: "science.sneaksanddata.com/nexus"

threshold:
  file: 70
  package: 70
  total: 75
      
exclude:
  paths:
    - \.pb\.go$           # excludes all protobuf generated files
    - ^pkg/generated      # exclude generated code
    - ^pkg/signals        # exclude signal handlers from sample controller
    - hack/*.go           # exclude hack folder
    - main.go             # exclude main file
