{{- if .Values.rbac.clusterRole.supervisor.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.clusteRole.supervisor" . }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- with .Values.rbac.clusterRole.supervisor.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.clusterRole.supervisor.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - verbs:
      - get
      - list
      - watch
      - delete
      - deletecollection
    apiGroups:
      - batch
    resources:
      - events
      - jobs
  - verbs:
      - get
      - list
      - watch
    apiGroups: [""]
    resources:
      - events
      - pods
{{- end }}