astra-cql-store:
  secure-connection-bundle-base64: ""
  gateway-user: ""
  gateway-password: ""
  keyspace: ""
  indexes-supported: true
scylla-cql-store:
  hosts: []
  port: ""
  user: ""
  password: ""
  local-dc: ""
  keyspace: ""
  indexes-supported: true
keyspaces-cql-store:
  hosts: []
  port: 9142
  ca-path: ""
  region: ""
  keyspace: ""
  use-irsa: false
cql-store-type: cassandra-scylla
kube-config-path: ""
resource-namespace: ""
log-level: ""
workers: ""
failure-rate-base-delay: ""
failure-rate-max-delay: ""
rate-limit-elements-per-second: ""
rate-limit-elements-burst: ""
