cql-store:
  secure-connection-bundle-base64: ""
  gateway-user: ""
  gateway-password: ""
kube-config-path: ""
resource-namespace: ""
log-level: ""
workers: ""
failure-rate-base-delay: ""
failure-rate-max-delay: ""
rate-limit-elements-per-second: ""
rate-limit-elements-burst: ""
